'use client';
import { useEffect, useState } from 'react';

export default function Account(){
 const [user,setUser]=useState(null),[mode,setMode]=useState('login'),[form,setForm]=useState({name:'',email:'',phone:'',password:'',confirm:''}),[orders,setOrders]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const [passwords,setPasswords]=useState({currentPassword:'',newPassword:'',confirmPassword:''});
 const load=async()=>{const r=await fetch('/api/customer/me',{cache:'no-store'});const x=await r.json();if(x.authenticated){setUser(x.user);const o=await fetch('/api/customer/orders',{cache:'no-store'});if(o.ok)setOrders(await o.json());}};
 useEffect(()=>{load()},[]);
 const submit=async e=>{e.preventDefault();setMsg('');if(mode==='register'&&form.password!==form.confirm)return setMsg('Passwords do not match.');setBusy(true);
  const endpoint=mode==='register'?'/api/customer/register':'/api/customer/login';
  const body=mode==='register'?{name:form.name,email:form.email,phone:form.phone,password:form.password}:{email:form.email,password:form.password};
  const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const x=await r.json();setBusy(false);if(!r.ok)return setMsg(x.error||'Could not continue.');await load();setForm({name:'',email:'',phone:'',password:'',confirm:''});
 };
 const changePassword=async e=>{e.preventDefault();setMsg('');if(passwords.newPassword!==passwords.confirmPassword)return setMsg('New passwords do not match.');const r=await fetch('/api/customer/change-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(passwords)});const x=await r.json();if(!r.ok)return setMsg(x.error||'Could not change password.');setMsg('Password changed successfully.');setPasswords({currentPassword:'',newPassword:'',confirmPassword:''});};
 const logout=async()=>{await fetch('/api/customer/logout',{method:'POST'});setUser(null);setOrders([]);};
 return <main className="adminPage"><header className="adminTop"><a href="/" className="adminBrand"><img src="/images/logo.png" alt=""/><span>Della's Closet</span></a><a className="back" href="/">Back to store →</a></header>
 <div className="adminWrap"><p className="eyebrow">CUSTOMER ACCOUNT</p><h1 style={{fontFamily:"'Playfair Display',serif",fontSize:'48px',fontWeight:500}}>Your Della's Closet account</h1>
 {!user?<div className="adminCard" style={{maxWidth:520,marginTop:25}}><h2>{mode==='login'?'Welcome back':'Create your account'}</h2>{mode==='register'&&<><label>Full name<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></>}<label>Email<input type="email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Password<input type="password" required minLength={8} value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label>{mode==='register'&&<label>Confirm password<input type="password" required minLength={8} value={form.confirm} onChange={e=>setForm({...form,confirm:e.target.value})}/></label>}<button className="adminButton" disabled={busy} onClick={submit}>{busy?'Please wait…':mode==='login'?'Sign in':'Create account'}</button>{msg&&<p className="adminMsg">{msg}</p>}<button className="reset" onClick={()=>{setMode(mode==='login'?'register':'login');setMsg('')}}>{mode==='login'?'Create a new account':'Already have an account? Sign in'}</button></div>
 :<><div className="adminGrid" style={{marginTop:25}}><section className="adminCard"><p className="eyebrow">PROFILE</p><h2>{user.name}</h2><p>{user.email}</p><p>{user.phone||'No phone number added'}</p><button className="reset" onClick={logout}>Sign out</button></section><form className="adminCard" onSubmit={changePassword}><p className="eyebrow">SECURITY</p><h2>Change password</h2><label>Current password<input type="password" required value={passwords.currentPassword} onChange={e=>setPasswords({...passwords,currentPassword:e.target.value})}/></label><label>New password<input type="password" required minLength={8} value={passwords.newPassword} onChange={e=>setPasswords({...passwords,newPassword:e.target.value})}/></label><label>Confirm new password<input type="password" required minLength={8} value={passwords.confirmPassword} onChange={e=>setPasswords({...passwords,confirmPassword:e.target.value})}/></label><button className="adminButton">Update password</button></form></div><section className="ordersPanel"><p className="eyebrow">MY ORDERS</p><h2>Order history</h2>{orders.length?orders.map(o=><article className="orderCard" key={o.id}><div className="orderHead"><div><strong>#{o.id.slice(-8).toUpperCase()}</strong><span>{new Date(o.createdAt).toLocaleString()}</span></div><strong>{o.status}</strong></div><div className="orderItems">{o.items.map(i=><span key={i.id}>{i.name} × {i.quantity} — ₦{(i.price*i.quantity).toLocaleString()}</span>)}</div><div className="orderTotal"><span>{o.deliveryZone}</span><strong>₦{o.total.toLocaleString()}</strong></div><a className="gpsLink" href={'/track/'+o.trackingToken}>Track order →</a></article>):<p className="muted">No orders yet.</p>}</section></>}
 </div></main>
}